Description: "Ecr template for mini-project."
Parameters: 
  RepoName: 
    Type: String
    Default: anthony-mini-project
    Description: Repository name for the miniproject

Resources:
  AnthonyMiniProject:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref RepoName
  
Outputs:
  ECROutput:
    Description: "ARN of ECR"
    Value: !Ref AnthonyMiniProject
    Export:
      Name: "anthony-mini-project-ecr"
