Parameters:
  VpcId:
    Description: "Default VpcId"
    Type: String
    Default: vpc-001084ff8ad166449

  SubnetId1:
    Description: "Default subnet 1"
    Type: String
    Default: subnet-0265a4fe3f9a4a89f

  SubnetId2:
    Description: "Default subnet 2"
    Type: String
    Default: subnet-0bc34574b93d7220f

Resources:
  HttpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Allow inbound traffic from the internet"
      GroupName: anthony-mini-project-security-group
      SecurityGroupIngress: 
        -  
          CidrIp: 0.0.0.0/0
          Description: "Inbound traffic from internet"
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      VpcId: !Ref VpcId
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: anthony-mini-project-loadbalancer
      Scheme: internet-facing
      SecurityGroups:
        - !GetAtt HttpSecurityGroup.GroupId
      Subnets: 
        - !Ref SubnetId1
        - !Ref SubnetId2
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Port: 9292
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref VpcId

Outputs:
  LoadbalancerUrl: 
    Description: "Load balancer url"
    Value: 
      !GetAtt LoadBalancer.DNSName
